name: Linter

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  linter:
    name: Linter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/lint_env.yaml
          environment-name: linter
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install package
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          micromamba list

      - name: Run flake8
        shell: bash -l {0}
        run: flake8 openxps

      - name: Run black
        shell: bash -l {0}
        run: black --diff --color openxps

      - name: Run isort
        shell: bash -l {0}
        run: isort --check-only openxps

      - name: Run pylint
        shell: bash -l {0}
        run: pylint openxps
