name: PyPI

on:
  push:
    tags:
      - v*

jobs:
  test:
    name: Build on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/deployment_env.yaml
          environment-name: test
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          micromamba list

      - name: PyPI Build and Upload
        shell: bash -l {0}
        run: |
          export OPENXPS_VERSION=${{ github.ref_name }}
          echo "::group::Building PyPI distribution for openxps $OPENXPS_VERSION"
          python -m build
          python -m twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} --repository pypi dist/*
          echo "::endgroup::"
